
// TODO: could improve in more readable and modular way
export const GET_AUTH_ERRORS = 'GET_AUTH_ERRORS';
export const CLEAR_AUTH_ERRORS = 'CLEAR_AUTH_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_VIDEOSTEPPER_BACKGROUND_IMAGE = 'SET_VIDEOSTEPPER_BACKGROUND_IMAGE';
export const SET_VIDEOSTEPPER_BACKGROUND_SIZE = 'SET_VIDEOSTEPPER_BACKGROUND_SIZE';
export const SET_VIDEOSTEPPER_BACKGROUND_COLOR = 'SET_VIDEOSTEPPER_BACKGROUND_COLOR';
export const SET_VIDEOSTEPPER_VIDEO = 'SET_VIDEOSTEPPER_VIDEO';
export const ADD_VIDEOSTEPPER_HEADERFOOTER = 'ADD_VIDEOSTEPPER_HEADERFOOTER';
export const UPDATE_VIDEOSTEPPER_HEADERFOOTERS = 'UPDATE_VIDEOSTEPPER_HEADERFOOTERS';
export const ADD_VIDEOSTEPPER_TEXT = 'ADD_VIDEOSTEPPER_TEXT';
export const UPDATE_VIDEOSTEPPER_TEXTS = 'UPDATE_VIDEOSTEPPER_TEXTS';
export const ADD_VIDEOSTEPPER_GIFIMAGE = 'ADD_VIDEOSTEPPER_GIFIMAGE';
export const UPDATE_VIDEOSTEPPER_GIFIMAGES = 'UPDATE_VIDEOSTEPPER_GIFIMAGES';
export const ADD_VIDEOSTEPPER_SUBTITLE = 'ADD_VIDEOSTEPPER_SUBTITLE';
export const UPDATE_VIDEOSTEPPER_SUBTITLES = 'UPDATE_VIDEOSTEPPER_SUBTITLES';
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';
export const SET_VIDEOSTEPPER_SCALE = 'SET_VIDEOSTEPPER_SCALE';
export const CLEAR_VIDEOSTEPPER_DATA = 'CLEAR_VIDEOSTEPPER_DATA';
